name: Builds and deploys packages to NPM

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup lerna and build
      run: |
          npm i -g lerna
          lerna bootstrap
          lerna exec --scope '*/ui' npm run build

    - name: Authenticate with registry and publish
      run: |
        echo "registry=//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
        echo "registry=http://registry.npmjs.org/" >> .npmrc
        ls -al
        cat .npmrc
        npm whoami
        lerna publish from-git -y
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}